### PR TITLE
Updating ReadME to include installation

### PR DESCRIPTION
**Pull request by sisu-callum**
Looks like the installation information is present in dbt_hub but not in this readme. Figured I'd create a PR to add it to the readme just in case that was unintended!

### CODE REVIEW

**Review by joellabes — CHANGES_REQUESTED** [review]
Good shout @sisu-callum! I don't want to have to remember to keep the version number up to date though 😬  - the utils package has this text, how about if we used that pattern? 

(The amount of backtickery going on broke GitHub's fancy suggestion mode, so you'll have to copy-paste like an animal sorry)

```
## Installation Instructions
Check [dbt Hub](https://hub.getdbt.com/dbt-labs/dbt_metrics/latest/) for the latest installation instructions, or [read the docs](https://docs.getdbt.com/docs/package-management) for more information on installing packages.
```

**Comment by joellabes** [comment]
Oh and also we'll need to work out your CLA status - I thought you had contributed to dbt Core in the past? Signing that should have cross-applied here. If you have them let me know and I'll dig into it.

**Comment by sisu-callum** [comment]
> Oh and also we'll need to work out your CLA status - I thought you had contributed to dbt Core in the past? Signing that should have cross-applied here. If you have them let me know and I'll dig into it.

Unfortunately not, didn't have dedicated time in the old role. Now I've got more time for work like this so hoping to contribute back more than I have in the past. I signed it last Friday so hopefully that is successfully appearing now!

**Review by joellabes — APPROVED** [review]
Perfect! Thank you 🙏

**Pull request merged**
