### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by joellabes**

### CODE REVIEW

**Comment by joellabes** [comment]
@drewbanin this is mostly stolen from the dbt-core repo; can you check that the CLA stuff is accurate before I merge this in please?

**Comment by joellabes** [comment]
I've also added the template Apache 2 licence text

**Comment by jtcohen6** [comment]
Happened to see this, so I'll share that:
- I'm planning to update dbt-core `CONTRIBUTING.md` to be much more generally about contributing to OSS at dbt Labs. (I'm also planning to move much of the tactical information, specific to testing, to `tests/README.md`)
- First draft: [Notion link](https://www.notion.so/dbtlabs/What-to-expect-when-you-re-contributing-to-dbt-or-any-open-source-project-f79aeb630499428f829f5590746e8825#8200f146d97c49bf91f9ca701da4cedd) — thanks for your feedback on it last week @joellabes! I owe everyone a second draft
- Other repositories can link to dbt-core's `CONTRIBUTING.md`, to avoid copy/pasting general expectations, and then include details that are specific to this particular repo (who should contribute, how to test, what to expect from review, etc)

**Review by drewbanin — APPROVED** [review]
@joellabes this is so comprehensive and so good! Approving this as-is, but also happy if we combine forces with the dbt-core contributing guide as @jtcohen6 mentioned above :)

**Comment by joellabes** [comment]
Thanks both! I'll ship this as-is and then we can streamline it soon

**Pull request merged**
