### PR TITLE
fix issue #146 - using the metric window functionality with time_grain='day'

### PR DESCRIPTION
**Pull request by JoeryV**
## What is this PR?
This is a:
- [ ] documentation update
- [x] bug fix with no breaking changes
- [ ] new functionality
- [ ] a breaking change

## Description & motivation
This PR fixes the bug described in issue #146. 
The `window_filter_date` will now be added regardless of the `time_grain` specified upon calling the metric.

How? The if condition that witheld the `window_filter_date` field from being added to the compiled query in case of `time_grain='day'` has been removed.

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

---
### Tenets to keep in mind 
- A metric value should be consistent everywhere that it is referenced
- We prefer generalized metrics with many dimensions over specific metrics with few dimensions
- It should be easier to use dbt’s metrics than it is to avoid them
- Organization and discoverability are as important as precision
- One-off models built to power metrics are an anti-pattern

### CODE REVIEW

**Comment by callum-mcdata** [comment]
@JoeryV would you be able to sign the CLA and also submit a `changie` log? You can find info on that in the CONTRIBUTING guide but the TLDR is you'll install a tool called `changie` and then run `changie new` in your terminal. It will walk you through creating an entry for the changelog.

**Comment by JoeryV** [comment]
I have signed the CLA and recreated your changie log entry! 👍 

Changie is actually missing from the CONTRIBUTING docs local to `dbt_metrics`, so I'll try to make an additional documentation change PR.

**Comment by callum-mcdata** [comment]
@JoeryV thanks for this one! It looks like we have a bug around external contributors accessing the Github Secrets for workflows so I'll add that to the backlog. In the meantime, I've run #150 which is the same as your code and confirmed that it works! So let's get this merged!

As a heads up, this bug will probably be held in `main` until we cut a new release at the EOW.

**Comment by JoeryV** [comment]
@callum-mcdata Thanks for the help callum! Glad to see such an enthusiastic team working on dbt! :)

**Pull request merged**
