### PR TITLE
Adding Prior Secondary Calculation

### PR DESCRIPTION
**Pull request by callum-mcdata**
## What is this PR?
This is a:
- [X] documentation update
- [ ] bug fix with no breaking changes
- [X] new functionality
- [ ] a breaking change

All pull requests from community contributors should target the `main` branch (default).

## Description & motivation
Based on #38 , this PR adds the `prior` secondary calculation in the new format. **This PR exists only to show the potential of what this would look like - it still has not been determined whether this should be included in the package**. 

We still need to determine whether this is worth the inclusion in the package or if we should offer this as example code for how people can override the package macros to provide their own secondary calculations.

## Checklist
- [X] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [X] Postgres
    - [ ] Redshift
    - [ ] Snowflake
- [X] I have updated the README.md (if applicable)
- [X] I have added tests & descriptions to my models (and macros if applicable)

---
### Tenets to keep in mind 
- A metric value should be consistent everywhere that it is referenced
- We prefer generalized metrics with many dimensions over specific metrics with few dimensions
- It should be easier to use dbt’s metrics than it is to avoid them
- Organization and discoverability are as important as precision
- One-off models built to power metrics are an anti-pattern

### CODE REVIEW

**Comment by callum-mcdata** [comment]
@aylr I had some flex time today so spun up this PR to reflect what the code might look like in the new codebase. We still need to determine whether this should be included in the package or just provide you (and other curious members of the community) with this code to override the package macros.

**Comment by callum-mcdata** [comment]
@joellabes do you have strong feelings on this one? More context in #127 and #38

**Comment by joellabes** [comment]
@callum-mcdata I'm not against the calculation itself, it seems like a straightforward ergonomic win if you want to do your calculations in the BI layer instead of letting dbt do it for you. I imagine @cafzal would want to talk about _why_ you want to do the calculations at the BI layer so that we can make it more compelling to stay in-package, but I don't think we need to block this addition on those grounds. 

Two comments: 
- I don't _love_ the name `prior` - I spent a long time trying to work out what it meant and ultimately checked the code. Should we just call it `lag` since that's all it does? Honestly my preferred name is `lookback`, but my dislike for inventing new names for things that already have names is in _strong_ conflict with the fact that `lead` and `lag` are silly names themselves 😅 
- In the original issue, it talked about being an extension to the PoP secondary calc, but this PR is its own secondary calc. What caused the change? Doesn't matter, just curious.

**Comment by joellabes** [comment]
👍 I have no strong feelings about any of this - go forth as you see fit!

**Comment by Aylr** [comment]
Thanks again @callum-mcdata.

**Pull request merged**
