### PR TITLE
Removing model introspection and adding allow_calendar_dimensions

### PR DESCRIPTION
**Pull request by callum-mcdata**
## What is this PR?
This is a:
- [x] documentation update
- [x] bug fix with no breaking changes
- [x] new functionality
- [ ] a breaking change

All pull requests from community contributors should target the `main` branch (default).

## Description & motivation
Related to issue #85 , this PR removes the default behavior of running queries against the data warehouse to validate the input. The only part where this introduced issues was in the use of calendar dimensions in the macro call. 

To support this use case while improving performance, we added the `allow_calendar_dimensions` parameter into the macro that can be set to true if the individual wants to add calendar dimensions. The package will only run a filtered column relation query IF this is set to true and will now only run 1 instead of multiple per metric.

Example:
```sql
  select *
  from 
  {{ metrics.calculate(
      metric('base_sum_metric'), 
      grain='day', 
      dimensions=['is_weekend'],
      allow_calendar_dimensions=true
  }}
```

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [X] Postgres
    - [ ] Redshift
    - [ ] Snowflake
- [X] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)

---
### Tenets to keep in mind 
- A metric value should be consistent everywhere that it is referenced
- We prefer generalized metrics with many dimensions over specific metrics with few dimensions
- It should be easier to use dbt’s metrics than it is to avoid them
- Organization and discoverability are as important as precision
- One-off models built to power metrics are an anti-pattern

### CODE REVIEW

**Comment by drewbanin** [comment]
@callum-mcdata this is groovy! When we last spoke about this, I was under the impression that this would be a project-level variable/config, not a metric-level argument! I don't _love_ the UX here because metrics consumers will probably not know if they need or want to supply this argument -- it feels like much more of a consideration for metric builders, not metric readers!

Is there a path to doing this as a dbt project-level variable, or env var, or something like that? Or does it need to be an argument to the metric call given the way that things are working today?

**Comment by callum-mcdata** [comment]
This is a good point - in our current implementation there is nothing stopping it from being a project variable or environment variable. Because of current dbt_server limitations around environment variables, I'll not go down that route but we can change it in the future.

In my mind this makes most sense to live as part of the metric definition, in which case I'd need to add it to parsed.py, unparsed.py, and schemas.py.

```yml
metrics:
  - name: metric_name
    label: metric
    model: ref('model')
    allow_calendar_dimensions: true
```

**Comment by callum-mcdata** [comment]
All righty, this has now been changed based on feedback from @drewbanin and @joellabes . 

Instead of this being a metric level config, we now support the `custom_calendar_dimension_list` in the project.yml. If this field is present, the dimensions within will be allowed in the calculate or develop query.

**Review by drewbanin — APPROVED** [review]
LGTM!

**Pull request merged**
