### PR TITLE
New `prior` secondary calculation

### PR DESCRIPTION
**Pull request by Aylr**
This PR implements a new `secondary_calculation` `prior` that pulls the value from the specified interval as discussed in #38

### CODE REVIEW

**Comment by callum-mcdata** [comment]
@Aylr I definitely haven't forgotten about this PR! The work for the v0.3.0 release ended up being a DOOZY. If it's all right with you, I can take this code you've got the PR for and integrate it into the new code structure so you don't have to rewrite this all.

I could probably tackle this in the next 2 weeks.

**Comment by Aylr** [comment]
@callum-mcdata that sounds like a great plan to me! Ping me if I can be of any help!

**Comment by Aylr** [comment]
@callum-mcdata Ping on this PR. I'd love to get it across the line. Please let me know how I can contribute.

**Comment by callum-mcdata** [comment]
@Aylr Thank you for the reminder on this one! As you can probably see, there has been a lot changed in the development of this package since we last talked. That being said, we are planning a release of v0.4.0 in the coming weeks that maybe we could slip this into if we can collab on it.

Additionally I've worked on this package enough to have formed opinions now, as opposed to it being my first month at dbt Labs when we last chatted! 😆 

### Digging Into The Use Case
Question for you as a user: does `prior` as a `comparison_strategy` of `period_over_period` make sense to you? 

Would it better serve the use case if this were its own secondary calculation? For example, what if you wanted to see the weekly metric from the prior year instead of last weeks ? I feel like a `prior` secondary calc could potentially support this behavior although it would be harder to implement

**Comment by Aylr** [comment]
@callum-mcdata I'd be delighted to collaborate to get this shipped. And congrats on getting more time at dbt labs under your belt!

I don't have strong opinion on the best UX here. As a contributor I initially picked what seemed like the best choice of a new `comparison_strategy`. Will you propose a psuedocode UX api here so we can iterate?

**Comment by callum-mcdata** [comment]
What do you think about:

`metrics.prior(interval=3, alias="last_month")`

**Functionality**: The secondary calc returns the value of the metric at a prior date. This value is at **the same grain** as provided to the macro. ex: If you are looking at a metric on the week level and select prior interval 4, this secondary_calc will give you the metric calculation from the 4 weeks ago. 
- `interval`: the number of intervals you want to look back

**Under The Hood**: We'd want to take advantage of the `offset` input in lag functionality to calculate this value.

------

Initially I thought about trying to do `metrics.prior(period="month",interval=3, alias="last_month")` but I don't believe that would work - by the time secondary calculations are being performed we've already aggregated to the grain provided to the macro. That means we'd have to be calendar aware in this calculation which is not a road we want to go down.

**Comment by callum-mcdata** [comment]
@Aylr closing this out for #127

**Pull request closed without merging**
